"""Self-host the three typefaces the site sets its text in.

Asking fonts.googleapis.com for them costs two extra origins, a connection
setup and a round trip before any text can be styled — on a phone that is most
of the Speed Index. Cinzel, Fraunces and Karla are all OFL, so the files can
simply live in the repository and be served from the same connection as
everything else.

The one thing worth knowing: all three are **variable** fonts. Google's CSS
declares one ``@font-face`` per requested weight, but the file behind every one
of them is the same — the 400 and the 600 of Cinzel are byte-identical. Written
out naively that is nine downloads of four distinct files. So faces are grouped
by (family, style, subset) and emitted once, with a weight *range*.

Vietnamese is dropped: its ``unicode-range`` never matches on a Spanish page, so
the browser would never fetch it, but the files would still sit in the repo.

    venv/bin/python scripts/fetch_fonts.py

Rewrites app/static/fonts/ and app/static/css/fonts.css. Both are committed;
this only has to run when a weight or a family changes.
"""

from __future__ import annotations

import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT_DIR = os.path.join(ROOT, "app", "static", "fonts")
CSS_PATH = os.path.join(ROOT, "app", "static", "css", "fonts.css")

GOOGLE_CSS = (
    "https://fonts.googleapis.com/css2"
    "?family=Cinzel:wght@400;600"
    "&family=Fraunces:ital,wght@0,400;0,600;1,400"
    "&family=Karla:wght@300;400;600;700"
    "&display=swap"
)

#: Google serves woff2 only to a browser that says it can take it.
UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36")

SKIP_SUBSETS = {"vietnamese"}


def fetch(url: str, ua: str | None = None) -> bytes:
    """curl rather than urllib: the system Python has no CA bundle here."""
    command = ["curl", "-sS", "--fail", url]
    if ua:
        command[1:1] = ["-A", ua]
    return subprocess.run(command, capture_output=True, check=True).stdout


def main() -> int:
    source = fetch(GOOGLE_CSS, UA).decode("utf-8")
    blocks = re.findall(r"/\*\s*([a-z-]+)\s*\*/\s*(@font-face\s*\{.*?\})", source, re.S)
    if not blocks:
        print("Google returned no @font-face blocks; is the family list still valid?")
        return 1

    # (family, style, subset) -> {weights, url, unicode_range}
    groups: dict[tuple[str, str, str], dict] = {}
    for subset, block in blocks:
        if subset in SKIP_SUBSETS:
            continue
        family = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        style = re.search(r"font-style:\s*(\w+)", block).group(1)
        weight = int(re.search(r"font-weight:\s*(\d+)", block).group(1))
        url = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)
        ranges = re.search(r"unicode-range:\s*([^;]+);", block).group(1)

        entry = groups.setdefault(
            (family, style, subset),
            {"weights": set(), "url": url, "range": ranges},
        )
        entry["weights"].add(weight)

    os.makedirs(FONT_DIR, exist_ok=True)
    for stale in os.listdir(FONT_DIR):
        if stale.endswith(".woff2"):
            os.remove(os.path.join(FONT_DIR, stale))

    faces, total = [], 0
    for (family, style, subset), entry in sorted(groups.items()):
        slug = family.lower().replace(" ", "-")
        name = f"{slug}{'-italic' if style == 'italic' else ''}-{subset}.woff2"
        path = os.path.join(FONT_DIR, name)
        open(path, "wb").write(fetch(entry["url"]))
        size = os.path.getsize(path)
        total += size
        print(f"  {name:34s} {size / 1024:6.1f} KB  {sorted(entry['weights'])}")

        low, high = min(entry["weights"]), max(entry["weights"])
        weight = f"{low}" if low == high else f"{low} {high}"
        faces.append(
            "@font-face {\n"
            f"  font-family: '{family}';\n"
            f"  font-style: {style};\n"
            f"  font-weight: {weight};\n"
            "  font-display: swap;\n"
            f"  src: url('../fonts/{name}') format('woff2');\n"
            f"  unicode-range: {entry['range']};\n"
            "}"
        )

    header = (
        "/* Self-hosted Cinzel, Fraunces and Karla (all OFL).\n"
        "   Generated by scripts/fetch_fonts.py — do not hand-edit.\n"
        "   One file per family, style and subset: these are variable fonts, so a\n"
        "   single file covers the whole weight range declared below. */\n\n"
    )
    open(CSS_PATH, "w", encoding="utf-8").write(header + "\n\n".join(faces) + "\n")
    print(f"\n{len(faces)} faces, {total / 1024:.0f} KB, "
          f"css {os.path.getsize(CSS_PATH) / 1024:.1f} KB")
    return 0


if __name__ == "__main__":
    sys.exit(main())
